name: slideme
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.0.2
  neopop: ^1.0.2
  google_fonts: ^6.3.1
  cloud_firestore: ^6.0.1
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  android_intent_plus: ^6.0.0
  sign_in_with_apple: ^7.0.1
  upi_pay: ^1.1.0
  liquid_progress_indicator_v2: ^0.5.0
  glassmorphism: ^3.0.0
  provider: ^6.1.5+1
  blurrycontainer: ^2.1.0
  glass_kit: ^4.0.1
  flutter_svg: ^2.2.1
  share_plus: ^12.0.1
  flutter_dotenv: ^6.0.0
  cloud_functions: ^6.0.3
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  gif: ^2.3.0
  flutter_gif: ^0.0.4
  video_player: ^2.10.0
  flutter_staggered_animations: ^1.1.1
  flutter_native_splash: ^2.4.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1  # ðŸ‘ˆ for your custom app icon

# ðŸ‘‡ Flutter Launcher Icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon.png"
  adaptive_icon_background: "#5FB567"
  adaptive_icon_foreground: "assets/images/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/mascot.png
    - assets/images/bg.png
    - assets/images/splash.mp4
    - assets/images/splash.gif
    - assets/images/splash.jpeg
    - assets/images/splash.png
    - assets/images/bgg.png
    - assets/images/mascot2.png
    - assets/images/mascot3.png
    - assets/images/mascot4.png
    - assets/images/googlelogo.png
    - assets/animations/Scene.json
    - assets/animations/money.json
    - assets/images/appicon.png



flutter_native_splash:
  color: "#5FB567"
  # Black background
  image: assets/images/splash.png # Path to your splash screen image
  android: true  # Enable splash screen for Android
  ios: true  # Enable splash screen for iOS
  fullscreen: true  # Use full-screen splash

  android_12:
    image: assets/images/splash.png           # prevents app icon from showing
    color: "#5FB567"
    fullscreen: true # Use full-screen splash
